### ISSUE TITLE
load scripts form authenticated source

### ISSUE THREAD

**Issue by mactrash** [collective/collective.disqus#34]
Anyone see the same warning in chrome?

**Comment by hvelarde** [comment]
which warning? be specific, please.

**Comment by mactrash** [comment]
@hvelarde this happen when the full plone run with https, and replace all http to disqus to https will fix it

**Comment by hvelarde** [comment]
you're not providing enough information; this is easy to fix, but I have no time to dig into it.

**Comment by fatrix** [comment]
I'm facing this issue too:
 ![image](https://user-images.githubusercontent.com/102456/45776522-6a81d080-bc53-11e8-8fed-bfbd3db22029.png)

count.js is configured to be loaded from http://_short_name_.disqus.com on line https://github.com/collective/collective.disqus/blob/master/collective/disqus/browser/disqus_summary_view.py#L25. This should be loaded from https. Otherwise for https sites in Chrome the user needs to agree with loading unsafe scripts.

Can I send a PR and somebody merges and creates a new release?

**Comment by philipsahli** [comment]
Sorry, but I just saw in comments.py the same issue and where the unauthenticated source comes from in my situation. Can we update the fix? Could push you the changes in the next two days.

https://github.com/collective/collective.disqus/blob/09f9ae545ddfa6d663ce6975ae097ee97803b3b6/collective/disqus/comments.py#L81
